### PR TITLE
Fix building on macOS 12

### PR DESCRIPTION
**Pull request by 0xTim**

### CODE REVIEW

**Comment by 0xTim** [comment]
@slashmo when you get a chance!

**Comment by slashmo** [comment]
@0xTim Thanks for the fix! Do we want to take the opportunity to rebase `feature/tracing` onto `upstream/main`?

**Comment by 0xTim** [comment]
Given all the errors with the new state machine and error codes let's hold off for now and give it some more bake time in the upstream

**Comment by slashmo** [comment]
Okay, sounds good! Merging this for now then.

**Pull request merged**
